# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eeef5ed1c943316a8f107d98a8596efa102309167ccf1ff3c4d2b3724b10f919dd958c7d924b82dc16df9e2ed8c6d8d9cc1b528bd8dcbc304a76d354723ec961

test:
  secret_key_base: 2a23f6cb50a13aaa36bcb09774b4a40b74eb20b919f4e9083b6b007762878d421d344f65a5ce1540578215c10bca1d1a0f0f4944977bb71a86ad1a9c13e769bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
